spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: DongunKim91
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  issuer: gauri7891@gmail.com
  secret_key: eW91cl92ZXJ5X3NlY3VyZV9zZWNyZXRfa2V5X2Zvcl9oczI1Nl9hbGdvcml0aG0h