spring:
  application:
    name: springboot-basic-board
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: DongunKim91

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mappers/*.xml

jwt:
  issuer: gauri7891@gmail.com
  secret_key: pyjWTd80kOTqOrK2lhYnztUIlS3v7VxD4z1iki2XCuX7wYcXpi8XMKU15BDIit9AdZUPYDRQm7Z4r5fLPNZ7Sg==
