
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: DongunKim91
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    encoding:
      force: true